### ISSUE TITLE
can not get video output..

### ISSUE THREAD

**Issue by aliendelon** [xuv/RasPiVJ#3]
Hey!
Thanks so much for this brilliant idea, but somehow i'm struggling to get this to finally work
I'm eventially got this all working - communication via web page etc.. but i can't get the video output at all
I havent checked HDMI but throug composite or TightVNC i get no video so far..
How is it suppose to work - when i'm clicking "Start Video" - it should start fullscreen?
I see just many commands in Terminal, reacting on what i'm doing
Any help is greatly appreciated! And hope 2016 will see an evolution of this great app!
Cheers!

**Comment by xuv** [comment]
Hey.
Thanks for your interest in this. And thank you also for the first bug report. :) Really appreciate. 
Actually, I have not tried with the composite output. Only with HDMI so far. But I don't see why this would not work. Especially if you see the terminal.

Have you started the node server? With this command: `node raspivj/raspivj.js`
What happens when you do this? Do you still use my videos or different ones?

And another thing. What version of Raspberry Pi do you have?

**Comment by aliendelon** [comment]
Hey again! 
Yes, the node server is started, then i see something like "listening on port 3000" then i connect from another computer to Pi's IP at port 3000 - and i see the control page, i can choose vids, play with sliders etc..  when i'm doing this i see in terminal lots of commands changing, but no output..
Is there any log? Probably i don't have codecs or something? 
Is there any way to simply check if "multiPlayer" is working at all?) 
Thanks and Happy New Year!!!

**Comment by xuv** [comment]
Ok. Good.
No need for codecs. The player should read the videos already in the `video/` folder perfectly fine.
When you have connected on the control page, have you clicked the "Start Video" button. I guess you did, but just asking. What happened then?

I you want to test the video player alone, go into the `scripts` folder and type this command:  
`sh start-multiPlayer.sh` and let me know what happens.

**Comment by aliendelon** [comment]
Ok, i got it
I simply put the "raspivj"  folder inside another folder - thats why script wasn't able to find the MultiPlayer
Now everything works as expected even on the composite output :)
Amazing stuff! 
Thanks so much to your support and your work!
Cheers!
![screen shot 2016-01-01 at 22 11 10](https://cloud.githubusercontent.com/assets/16496752/12071900/db827e74-b0d5-11e5-802a-41147f840ac5.png)

**Comment by xuv** [comment]
Ho. Great. Glad to know it worked. 
And sorry for the trouble. I should make things more flexible. So you could install it wherever you want. As I said in the readme, I mostly built this for myself. So not very flexible yet. 
I'm also thinking of making dedicated PI image that you would just have to copy on an SD card and run it.
But I did not have time or a deadline to do this. Looking forward for your feedback. See you.
